language: python
python:
  - "2.6"
  - "2.7"
  #- "3.2"
  # command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
script: 
  - python gradePerson.py names.txt
  - python gradePerson_test.py